### ISSUE TITLE
Converting Psi4 (or other QC tools) electron densities to spherical harmonics

### ISSUE THREAD

**Issue by JSLJ23** [JoshRackers/equivariant_electron_density#3]
I was wondering is there a way whereby the electron densities from Psi4's wave function objects can be fitted to spherical harmonic basis functions and if this could be generalised to other QC methods, DFT, MP2, CCSD(T), etc..., basis sets, and other quantum chemistry tools?
Also, if there's a part of the code that does this, could you kindly point me to it and perhaps give a slight explanation to what is involved in this change of basis?
Thank you.

**Comment by JoshRackers** [comment]
Good question. That is exactly what is done [here](https://github.com/JoshRackers/equivariant_electron_density/blob/main/generate_density_datasets/densityfit_q.py).

For an explanation, see section 1.1.2 in the supplement of the [paper](https://iopscience.iop.org/article/10.1088/2632-2153/acb314/meta)

**Comment by JSLJ23** [comment]
Thank you for sharing this and my apologies for the delayed reply, I spent some time looking into this but only revisiting it now.

**Comment by JSLJ23** [comment]
Regarding the isolated atom densities for generating training data for other QC methods, DFT, MP2, CCSD(T), etc..., is there a standardised way for obtaining those spherical harmonic coefficients too? And once they're obtained, are they just directly subtracted from the matching L&M spherical harmonic terms in the molecular training data?

**Comment by JoshRackers** [comment]
Good question! You should perform a reference calculation in the isolated
atoms with the level of theory and basis set you want. The best way to do
this is to create a version of the basis set in which you delete all of the
non-S basis functions. This will ensure that you get a reference density
which is correctly exactly spherically symmetric.

**Comment by JSLJ23** [comment]
Ok got it. Could you elaborate a bit more on the rationale behind this part "delete all of the non-S basis functions"? Why is this necessary to get the isolated single atom density?

**Comment by JoshRackers** [comment]
Sure thing. The reason to do this is to avoid density-fitting artifacts in
non-spherically symmetric basis functions. Because the potential of an
isolated nucleus is spherically symmetric, the density should be as well.
However, unless you specifically tell psi4 this symmetry, it will produce
coefficients for non-S functions that are non-zero. While these
coefficients are likely to be small, they are artifacts, so best to
eliminate them altogether by restricting the basis.

You're welcome to try this test yourself and compare coefficients for both
bases. The S function coefficients should be very similar and the non-S
coefficients in the "full" basis should be very close to zero.

**Comment by JSLJ23** [comment]
Thank you for the detailed explanation, I'll give it a shot for self learning purposes too. 👍
